### ISSUE TITLE
Store admin can edit item

### ISSUE THREAD

**Issue by bethsebian** [TheObtuseAutodidact/the_pivot#59]
As a store admin
when I log in,
and I visit my dashboard,
within the item section, 
when I click on the link to edit an item,
I see a form to edit an item, 
I update the item title,
I update the item description, 
I update the item photo, 
I update the category from the list, 
and I click on submit
I see a notice that my item was successfully edited, 
and I’m redirected to my dashboard, 
and I see the item I edited and it reflects my changes.

**Comment by TheObtuseAutodidact** [comment]
maybe separate tests for each edited field

**Comment by bethsebian** [comment]
I like that idea
